name: time_keeper
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.1.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Models
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

  # State management
  flutter_bloc: ^8.1.5

  # Service locator
  get_it: ^7.6.7

  # Persistence
  objectbox: ^2.5.1
  objectbox_flutter_libs: any
  auto_route: ^8.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting
  flutter_lints: ^2.0.0

  # Code generation
  build_runner: ^2.4.9
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  objectbox_generator: any
  auto_route_generator: ^8.0.0
flutter:
  uses-material-design: true